title: OER GitHub Tutorial
author: Sophie Matter
logo: logo.svg
execute:
  execute_notebooks: force
latex:
  latex_documents:
    targetname: book.tex
bibtex_bibfiles:
- references.bib
repository:
  branch: main
  url: https://github.com/smatts/jupyter-oer-template
html:
  use_issues_button: true
  use_repository_button: true
